name: R-CMD-check

on: [push, pull_request]

jobs:
  R-CMD-check:
    runs-on: macOS-latest

    name: R-CMD-check
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps(dependencies = TRUE)

      - name: Check package
        run: |
          devtools::check()

      - name: Check CRAN submission standards
        run: |
          devtools::check_cran()

      - name: Build pkgdown site
        run: |
          install.packages('pkgdown')
          pkgdown::build_site()

      - name: Build README
        run: |
          devtools::build_readme()

      - name: Run tests
        run: |
          install.packages('testthat')
          testthat::test_dir('tests/testthat')

      - name: Build vignettes
        run: |
          devtools::build_vignettes()
